/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "xdjndwdeepruvhprtjvt"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkam5kd2RlZXBydXZocHJ0anZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTQ0NjMsImV4cCI6MjA3NDU3MDQ2M30.w4NYWDsnha-AjdkfBHSmGMhZAAd4PmGdgwDUIdzhiSo"